const messages = {
  title: ["Conhecimento dos projetos", "Project knowledge", "Conocimiento de los proyectos"],
  profile: ["Perfil global", "Global profile", "Perfil global"],
  catalog: ["Catálogo", "Catalog", "Catálogo"],
  search: ["Busca integrada", "Unified search", "Búsqueda integrada"],
  archive: ["Arquivo", "Archive", "Archivo"],
  sync: ["Exportação incremental", "Incremental export", "Exportación incremental"],
  refresh: ["Atualizar", "Refresh", "Actualizar"],
  save: ["Salvar", "Save", "Guardar"],
  approve: ["Aprovar preferência", "Approve preference", "Aprobar preferencia"],
  reject: ["Rejeitar", "Reject", "Rechazar"],
  pending: ["Aguardando revisão", "Awaiting review", "Pendiente de revisión"],
  accepted: ["Aprovada", "Approved", "Aprobada"],
  rejected: ["Rejeitada", "Rejected", "Rechazada"],
  forgotten: ["Esquecida", "Forgotten", "Olvidada"],
  profileHint: ["Preferências explícitas, gerais ou recorrentes em dois projetos, podem ser selecionadas automaticamente. Conflitos e instruções temporárias ficam para revisão opcional. Você pode desativar a seleção automática.", "Explicit preferences that are general or recur across two projects can be selected automatically. Conflicts and temporary instructions remain for optional review. Automatic selection can be disabled.", "Las preferencias explícitas, generales o recurrentes en dos proyectos pueden seleccionarse automáticamente. Los conflictos y las instrucciones temporales quedan para revisión opcional. Puedes desactivar la selección automática."],
  eligible: ["Evidência geral ou recorrente", "General or recurring evidence", "Evidencia general o recurrente"],
  replaces: ["Há preferências aprovadas para este assunto. Aprovar substitui as anteriores que mantêm o texto original; edições manuais são preservadas.", "This topic has approved preferences. Approval supersedes predecessors that retain their original statement; manual edits are preserved.", "Este tema tiene preferencias aprobadas. La aprobación sustituye las anteriores que conservan su declaración original; se preservan las ediciones manuales."],
  single: ["Evidência de um projeto; revise o alcance", "One project; review the scope", "Un proyecto; revise el alcance"],
  empty: ["Nenhum resultado", "No results", "Sin resultados"],
  contribute: ["Contribuir com sugestões de preferências", "Contribute preference suggestions", "Contribuir sugerencias de preferencias"],
  consume: ["Usar preferências globais aprovadas", "Use approved global preferences", "Usar preferencias globales aprobadas"],
  discovery: ["Permitir consultas explícitas a outros projetos", "Allow explicit queries to other projects", "Permitir consultas explícitas a otros proyectos"],
  visible: ["Exibir este projeto para descoberta", "Expose this project for discovery", "Mostrar este proyecto para descubrimiento"],
  catalogHint: ["IDs preservam o histórico. Checkouts com o mesmo remoto continuam separados até você associá-los. A descoberta entre projetos começa desativada.", "IDs preserve history. Checkouts sharing a remote remain separate until you associate them. Cross-project discovery starts disabled.", "Los IDs preservan el historial. Los checkouts del mismo remoto permanecen separados hasta asociarlos. El descubrimiento entre proyectos comienza desactivado."],
  name: ["Nome", "Name", "Nombre"],
  description: ["Resumo do projeto", "Project summary", "Resumen del proyecto"],
  associate: ["Associar outro checkout", "Associate another checkout", "Asociar otro checkout"],
  query: ["Decisão, arquivo ou assunto", "Decision, file or topic", "Decisión, archivo o tema"],
  searchHint: ["Memórias e documentos competem pelo mesmo orçamento. Os vínculos expandem a busca em até um salto. A origem e o motivo aparecem em cada resultado.", "Memories and documents compete within one budget. Links expand retrieval by at most one hop. Each result explains its source and reason.", "Las memorias y documentos compiten dentro del mismo presupuesto. Los enlaces amplían la búsqueda como máximo un salto. Cada resultado explica su origen y motivo."],
  restore: ["Restaurar", "Restore", "Restaurar"],
  maintain: ["Prévia de manutenção", "Maintenance preview", "Vista previa de mantenimiento"],
  applyMaintenance: ["Arquivar itens da prévia", "Archive previewed items", "Archivar elementos de la vista previa"],
  maintenanceHint: ["Sugere handoffs automáticos sem uso há 90 dias. Arquivar preserva conteúdo e versões; notas manuais e fixadas são mantidas.", "Suggests automatic handoffs unused for 90 days. Archiving preserves content and versions; manual and pinned notes are kept.", "Sugiere handoffs automáticos sin uso durante 90 días. Archivar preserva el contenido y las versiones; las notas manuales y fijadas se conservan."],
  preview: ["Escolher pasta e visualizar", "Choose folder and preview", "Elegir carpeta y previsualizar"],
  applyExport: ["Aplicar exportação", "Apply export", "Aplicar exportación"],
  syncHint: ["Atualiza uma projeção Markdown estável. Alterações locais bloqueiam a exportação e são listadas como conflitos. Arquivos de notas removidas são preservados; a edição Markdown não altera o banco.", "Updates a stable Markdown projection. Local changes block the export and appear as conflicts. Files for removed notes are retained; editing Markdown does not change the database.", "Actualiza una proyección Markdown estable. Los cambios locales bloquean la exportación y aparecen como conflictos. Se conservan los archivos de notas eliminadas; editar Markdown no cambia la base de datos."],
  exported: ["Exportação concluída", "Export completed", "Exportación completada"],
  conflicts: ["Conflitos; preserve ou mova as alterações locais antes de tentar novamente", "Conflicts; preserve or move local changes before retrying", "Conflictos; conserve o mueva los cambios locales antes de reintentar"],
  history: ["Histórico e aplicabilidade", "History and applicability", "Historial y aplicabilidad"],
  category: ["Categoria", "Category", "Categoría"],
  tags: ["Aplicável às stacks (separadas por vírgula)", "Applicable stacks (comma separated)", "Stacks aplicables (separados por comas)"],
  feedback: ["Utilidade", "Usefulness", "Utilidad"],
  helpful: ["Útil", "Helpful", "Útil"],
  notHelpful: ["Pouco útil", "Not helpful", "Poco útil"],
  wrong: ["Incorreta; excluir da recuperação", "Wrong; exclude from retrieval", "Incorrecta; excluir de la recuperación"],
  state: ["Estado", "State", "Estado"],
  active: ["Ativa", "Active", "Activa"],
  archived: ["Arquivada", "Archived", "Archivada"],
  stale: ["Desatualizada", "Stale", "Desactualizada"],
  superseded: ["Substituída", "Superseded", "Sustituida"],
  replacement: ["ID da nota substituta", "Replacement note ID", "ID de la nota sustituta"],
  relations: ["Vínculos (IDs separados por vírgula)", "Relationships (comma separated IDs)", "Relaciones (IDs separados por comas)"],
  usage: ["Consultas registradas", "Recorded accesses", "Consultas registradas"],
  versions: ["Versões do conteúdo", "Content versions", "Versiones del contenido"],
  preference: ["Preferência", "Preference", "Preferencia"],
  procedure: ["Procedimento", "Procedure", "Procedimiento"],
  gotcha: ["Armadilha", "Gotcha", "Trampa"],
  lesson: ["Aprendizado", "Lesson", "Aprendizaje"],
} as const;
export const intelligenceCopy = (locale: string) => {
  const index = locale.startsWith("pt") ? 0 : locale.startsWith("es") ? 2 : 1;
  return Object.fromEntries(Object.entries(messages).map(([key, values]) => [key, values[index]])) as Record<keyof typeof messages, string>;
};
