const pt = {
  scopeLabel: "Escopo da memória", global: "Global", projectScope: "Este projeto", globalEnabled: "Memória global", globalHint: "Preferências e fatos úteis em todos os projetos. Só você salva aqui; a captura automática permanece no projeto.", projectHint: "Decisões e continuidade deste projeto. O agente combina as notas relevantes com a memória global.", globalSearch: "Buscar nas notas globais…", globalEmpty: "Sua memória global começa aqui.", globalEmptyHint: "Salve preferências reutilizáveis. Afixe uma nota para incluí-la como contexto básico, respeitando o orçamento.", globalPlaceholder: "Preferências ou fatos úteis em qualquer projeto…", scopeSaved: "Destino", storageTitle: "Onde suas memórias são salvas", storageHint: "Banco SQLite local. Global e projetos têm espaços separados neste arquivo. As notas não são arquivos Markdown; você pode exportar uma cópia para seu vault.", openStorage: "Abrir pasta", copyPath: "Copiar caminho", copiedPath: "Caminho copiado.", globalBudgetHint: "Limite da parcela global, sempre dentro do orçamento total do projeto.", projectBudgetHint: "Teto total para notas globais, notas do projeto e documentos recuperados juntos.", pinHint: "Notas afixadas formam uma base de contexto; não se repetem na mesma conversa até serem alteradas ou relembradas.", exportMarkdown: "Exportar Markdown", exportTitle: "Escolher pasta para exportar as notas", exportHint: "Cria uma pasta nova com uma cópia das notas e um índice de links para o grafo do Obsidian. Não sincroniza alterações de volta.", exported: "Notas exportadas para", storageError: "Não foi possível acessar o armazenamento.",
  title: "Memória compartilhada", documents: "Documentos", intro: "Conhecimento global e de cada projeto para Claude, Codex e Gemini.", project: "Projeto da memória", noProject: "Selecione um projeto para abrir sua memória.", desktop: "A memória compartilhada está disponível no aplicativo desktop.",
  enabled: "Memória do projeto", enabledHint: "Recupera contexto relevante nas próximas interações.", capture: "Captura automática", captureHint: "Guarda continuidade das respostas concluídas no chat visual. No terminal, o agente pode salvar via MCP.", on: "Ativada", off: "Desativada",
  budget: "Orçamento de contexto", budgetHint: "Limite estimado por recuperação, calculado em bytes ÷ 4. O conteúdo enviado ao agente utiliza contexto.", budgetRange: "De 256 a 2.000 tokens, em números inteiros.", apply: "Aplicar orçamento", budgetInvalid: "Use um valor entre 256 e 2.000 tokens.", tokens: "tokens estimados", preferences: "Preferências de memória",
  notes: "Notas", newNote: "Nova nota", search: "Buscar nas notas do projeto…", refresh: "Atualizar memória", empty: "A memória deste projeto começa aqui.", emptyHint: "Salve decisões e fatos ou deixe a captura registrar pontos de continuidade após as próximas respostas.", noResults: "Nenhuma nota corresponde à busca.", clearSearch: "Limpar busca",
  handoff: "Continuidade", decision: "Decisão", fact: "Fato", all: "Todos os tipos", titleField: "Título da nota", contentField: "Conteúdo da nota", kindField: "Tipo de nota", titlePlaceholder: "Uma decisão ou informação útil", contentPlaceholder: "Registre contexto que vale a pena reutilizar neste projeto…",
  save: "Salvar nota", saving: "Salvando…", cancel: "Cancelar", edit: "Editar nota", pin: "Afixar nota", unpin: "Desafixar nota", pinned: "Afixada", delete: "Excluir nota", confirmDelete: "Excluir esta nota da memória?", deleteHint: "A nota deixará de ser recuperada nas próximas interações.", back: "Voltar às notas",
  manual: "Salva por você", automatic: "Captura automática", mcp: "Conteúdo do agente", origin: "Origem", provider: "Provedor", updated: "Atualizada", revision: "Revisão", sourceSession: "Sessão de origem", openSession: "Abrir sessão de origem", unverified: "Não verificada", confirmed: "Confirmada por você", noContent: "Esta nota não possui conteúdo.", validation: "Preencha o título e o conteúdo da nota.",
  local: "Armazenamento local, separado por projeto.", retrieval: "Contexto relevante recuperado sob demanda. Notas completas ficam disponíveis por MCP; não são anexadas integralmente a cada mensagem.", readMore: "Como o contexto é usado", loading: "Carregando memória…", loadError: "Não foi possível atualizar a memória.", retry: "Tentar novamente", saved: "Nota salva.", deleted: "Nota excluída.", configurationSaved: "Preferências salvas.",
  recall: "Relembrar nesta conversa", recallHint: "Permite recuperar novamente as notas relevantes na próxima mensagem desta conversa.", recalled: "A próxima mensagem poderá recuperar novamente o contexto relevante.", captureReview: "Pontos de continuidade são registros do agente. Revise antes de tratá-los como fatos confirmados.",
  saveAnswer: "Guardar resposta na memória", savedToMemory: "Resposta guardada na memória do projeto.", viewMemory: "Abrir memória do projeto", actionFailure: "Não foi possível guardar a resposta.",
  responseExcerpt: "Trecho da resposta; consulte a sessão de origem para o conteúdo completo.",
  titleTooLong: "O título pode ter até 240 bytes. Reduza o texto.", contentTooLong: "A nota pode ter até 12.000 bytes. Divida o conteúdo em notas menores.",
  short: "Memória", contextError: "Memória indisponível", retrieved: "Notas recuperadas", duplicates: "Notas não repetidas",
};
type Copy = { [Key in keyof typeof pt]: string };
const en: Copy = {
  scopeLabel: "Memory scope", global: "Global", projectScope: "This project", globalEnabled: "Global memory", globalHint: "Preferences and facts useful across projects. Only you save here; automatic capture stays in the project.", projectHint: "Decisions and continuity for this project. The agent combines relevant notes with global memory.", globalSearch: "Search global notes…", globalEmpty: "Your global memory starts here.", globalEmptyHint: "Save reusable preferences. Pin a note to include it as baseline context within the budget.", globalPlaceholder: "Preferences or facts useful in any project…", scopeSaved: "Destination", storageTitle: "Where your memories are saved", storageHint: "Local SQLite database. Global and project notes have separate namespaces in this file. Notes are not Markdown files; you can export a copy to your vault.", openStorage: "Open folder", copyPath: "Copy path", copiedPath: "Path copied.", globalBudgetHint: "Limit for the global share, always inside the project's total budget.", projectBudgetHint: "Total ceiling for global notes, project notes and retrieved documents together.", pinHint: "Pinned notes provide baseline context; they are not repeated in a conversation until changed or recalled.", exportMarkdown: "Export Markdown", exportTitle: "Choose a folder to export notes", exportHint: "Creates a new folder with a copy of the notes and a linked index for the Obsidian graph. Changes are not synced back.", exported: "Notes exported to", storageError: "Could not access storage.",
  title: "Shared memory", documents: "Documents", intro: "Global and project knowledge for Claude, Codex and Gemini.", project: "Memory project", noProject: "Select a project to open its memory.", desktop: "Shared memory is available in the desktop app.",
  enabled: "Project memory", enabledHint: "Retrieves relevant context in future interactions.", capture: "Automatic capture", captureHint: "Saves handoffs from completed responses in visual chat. In the terminal, the agent can save through MCP.", on: "Enabled", off: "Disabled",
  budget: "Context budget", budgetHint: "Estimated limit per retrieval, calculated as bytes ÷ 4. Content sent to the agent uses context.", budgetRange: "From 256 to 2,000 tokens, in whole numbers.", apply: "Apply budget", budgetInvalid: "Enter a value between 256 and 2,000 tokens.", tokens: "estimated tokens", preferences: "Memory preferences",
  notes: "Notes", newNote: "New note", search: "Search this project's notes…", refresh: "Refresh memory", empty: "This project's memory starts here.", emptyHint: "Save decisions and facts or let capture record handoff notes after future responses.", noResults: "No notes match your search.", clearSearch: "Clear search",
  handoff: "Handoff", decision: "Decision", fact: "Fact", all: "All types", titleField: "Note title", contentField: "Note content", kindField: "Note type", titlePlaceholder: "A useful decision or piece of information", contentPlaceholder: "Record context worth reusing in this project…",
  save: "Save note", saving: "Saving…", cancel: "Cancel", edit: "Edit note", pin: "Pin note", unpin: "Unpin note", pinned: "Pinned", delete: "Delete note", confirmDelete: "Delete this note from memory?", deleteHint: "The note will no longer be retrieved in future interactions.", back: "Back to notes",
  manual: "Saved by you", automatic: "Automatic capture", mcp: "Agent content", origin: "Source", provider: "Provider", updated: "Updated", revision: "Revision", sourceSession: "Source session", openSession: "Open source session", unverified: "Unverified", confirmed: "Confirmed by you", noContent: "This note has no content.", validation: "Enter a title and content for this note.",
  local: "Stored locally, separated by project.", retrieval: "Relevant context is retrieved on demand. Full notes are available through MCP; they are not appended in full to every message.", readMore: "How context is used", loading: "Loading memory…", loadError: "Could not refresh memory.", retry: "Try again", saved: "Note saved.", deleted: "Note deleted.", configurationSaved: "Preferences saved.",
  recall: "Recall in this conversation", recallHint: "Allows relevant notes to be retrieved again with this conversation's next message.", recalled: "The next message can retrieve relevant context again.", captureReview: "Handoff notes are records written by the agent. Review them before treating them as confirmed facts.",
  saveAnswer: "Save response to memory", savedToMemory: "Response saved to project memory.", viewMemory: "Open project memory", actionFailure: "Could not save the response.",
  responseExcerpt: "Response excerpt; see the source session for the complete content.",
  titleTooLong: "The title can contain up to 240 bytes. Shorten the text.", contentTooLong: "A note can contain up to 12,000 bytes. Split the content into smaller notes.",
  short: "Memory", contextError: "Memory unavailable", retrieved: "Retrieved notes", duplicates: "Notes not repeated",
};
const es: Copy = {
  scopeLabel: "Ámbito de memoria", global: "Global", projectScope: "Este proyecto", globalEnabled: "Memoria global", globalHint: "Preferencias y hechos útiles en todos los proyectos. Solo tú guardas aquí; la captura automática permanece en el proyecto.", projectHint: "Decisiones y continuidad de este proyecto. El agente combina notas relevantes con la memoria global.", globalSearch: "Buscar notas globales…", globalEmpty: "Tu memoria global empieza aquí.", globalEmptyHint: "Guarda preferencias reutilizables. Fija una nota para incluirla como contexto base dentro del presupuesto.", globalPlaceholder: "Preferencias o hechos útiles en cualquier proyecto…", scopeSaved: "Destino", storageTitle: "Dónde se guardan tus memorias", storageHint: "Base SQLite local. Global y proyectos tienen espacios separados en este archivo. Las notas no son archivos Markdown; puedes exportar una copia a tu vault.", openStorage: "Abrir carpeta", copyPath: "Copiar ruta", copiedPath: "Ruta copiada.", globalBudgetHint: "Límite de la parte global, siempre dentro del presupuesto total del proyecto.", projectBudgetHint: "Límite total para notas globales, notas del proyecto y documentos recuperados juntos.", pinHint: "Las notas fijadas forman una base de contexto; no se repiten en la conversación hasta que se modifiquen o se recuerden.", exportMarkdown: "Exportar Markdown", exportTitle: "Elegir carpeta para exportar notas", exportHint: "Crea una carpeta nueva con una copia de las notas y un índice enlazado para el grafo de Obsidian. Los cambios no se sincronizan de vuelta.", exported: "Notas exportadas a", storageError: "No se pudo acceder al almacenamiento.",
  title: "Memoria compartida", documents: "Documentos", intro: "Conocimiento global y de cada proyecto para Claude, Codex y Gemini.", project: "Proyecto de memoria", noProject: "Selecciona un proyecto para abrir su memoria.", desktop: "La memoria compartida está disponible en la aplicación de escritorio.",
  enabled: "Memoria del proyecto", enabledHint: "Recupera contexto relevante en las próximas interacciones.", capture: "Captura automática", captureHint: "Guarda continuidad de respuestas completadas en el chat visual. En el terminal, el agente puede guardar por MCP.", on: "Activada", off: "Desactivada",
  budget: "Presupuesto de contexto", budgetHint: "Límite estimado por recuperación, calculado en bytes ÷ 4. El contenido enviado al agente utiliza contexto.", budgetRange: "De 256 a 2.000 tokens, en números enteros.", apply: "Aplicar presupuesto", budgetInvalid: "Usa un valor entre 256 y 2.000 tokens.", tokens: "tokens estimados", preferences: "Preferencias de memoria",
  notes: "Notas", newNote: "Nueva nota", search: "Buscar en las notas del proyecto…", refresh: "Actualizar memoria", empty: "La memoria de este proyecto empieza aquí.", emptyHint: "Guarda decisiones y hechos o deja que la captura registre notas de continuidad después de las próximas respuestas.", noResults: "Ninguna nota coincide con la búsqueda.", clearSearch: "Limpiar búsqueda",
  handoff: "Continuidad", decision: "Decisión", fact: "Hecho", all: "Todos los tipos", titleField: "Título de la nota", contentField: "Contenido de la nota", kindField: "Tipo de nota", titlePlaceholder: "Una decisión o información útil", contentPlaceholder: "Registra contexto que valga la pena reutilizar en este proyecto…",
  save: "Guardar nota", saving: "Guardando…", cancel: "Cancelar", edit: "Editar nota", pin: "Fijar nota", unpin: "Desfijar nota", pinned: "Fijada", delete: "Eliminar nota", confirmDelete: "¿Eliminar esta nota de la memoria?", deleteHint: "La nota dejará de recuperarse en las próximas interacciones.", back: "Volver a las notas",
  manual: "Guardada por ti", automatic: "Captura automática", mcp: "Contenido del agente", origin: "Origen", provider: "Proveedor", updated: "Actualizada", revision: "Revisión", sourceSession: "Sesión de origen", openSession: "Abrir sesión de origen", unverified: "Sin verificar", confirmed: "Confirmada por ti", noContent: "Esta nota no tiene contenido.", validation: "Completa el título y el contenido de la nota.",
  local: "Almacenamiento local, separado por proyecto.", retrieval: "El contexto relevante se recupera bajo demanda. Las notas completas están disponibles por MCP; no se adjuntan completas a cada mensaje.", readMore: "Cómo se usa el contexto", loading: "Cargando memoria…", loadError: "No se pudo actualizar la memoria.", retry: "Intentar de nuevo", saved: "Nota guardada.", deleted: "Nota eliminada.", configurationSaved: "Preferencias guardadas.",
  recall: "Recordar en esta conversación", recallHint: "Permite recuperar de nuevo las notas relevantes con el próximo mensaje de esta conversación.", recalled: "El próximo mensaje podrá recuperar de nuevo el contexto relevante.", captureReview: "Las notas de continuidad son registros del agente. Revísalas antes de tratarlas como hechos confirmados.",
  saveAnswer: "Guardar respuesta en la memoria", savedToMemory: "Respuesta guardada en la memoria del proyecto.", viewMemory: "Abrir memoria del proyecto", actionFailure: "No se pudo guardar la respuesta.",
  responseExcerpt: "Extracto de la respuesta; consulta la sesión de origen para el contenido completo.",
  titleTooLong: "El título puede tener hasta 240 bytes. Reduce el texto.", contentTooLong: "La nota puede tener hasta 12.000 bytes. Divide el contenido en notas más pequeñas.",
  short: "Memoria", contextError: "Memoria no disponible", retrieved: "Notas recuperadas", duplicates: "Notas no repetidas",
};
export function memoryCopy(locale: string): Copy {
  const index=locale.startsWith("pt")?0:locale.startsWith("es")?2:1;
  return {...(index===0?pt:index===2?es:en),
    globalHint:["Preferências úteis em vários projetos. A seleção automática pode salvar preferências explícitas com evidências; você também pode salvar notas manualmente.","Preferences useful across projects. Automatic selection can save explicit preferences with evidence; you can also save notes manually.","Preferencias útiles en varios proyectos. La selección automática puede guardar preferencias explícitas con evidencias; también puedes guardar notas manuales."][index],
    captureReview:["A seleção organiza o contexto automaticamente. Notas do agente são evidências históricas; confirme arquivos e resultados ao reutilizá-las.","Selection organizes context automatically. Agent notes are historical evidence; verify files and results when reusing them.","La selección organiza el contexto automáticamente. Las notas del agente son evidencias históricas; comprueba archivos y resultados al reutilizarlas."][index],
  };
}
