const pt = {
  chat: "Conversa", native: "Terminal nativo", ready: "Seu próximo projeto começa aqui", intro: "Planeje, construa e revise com seus agentes no mesmo lugar.", latest: "Ir para o final", you: "Você", attach: "Adicionar arquivos ou imagens", add: "Adicionar contexto", files: "Arquivos e imagens", goal: "Objetivo da conversa", goalPlaceholder: "Qual resultado você quer alcançar?", goalHint: "Incluído nas próximas mensagens desta conversa.", sketch: "Desenhar", sketchTitle: "Esboço para o agente", sketchAdd: "Anexar esboço", clear: "Limpar", cancel: "Cancelar", remove: "Remover", drop: "Solte os arquivos para anexar", upload: "Preparando anexos…", maxFiles: "Use até 12 arquivos, de até 20 MB cada e 40 MB no total.", searching: "Buscar na conversa", search: "Buscar", export: "Exportar conversa", copy: "Copiar", copied: "Copiado", retry: "Tentar novamente", starting: "Conectando ao agente…", working: "Agente trabalhando…", stop: "Parar resposta", stopped: "Resposta interrompida", done: "Concluído", tools: "Atividade do agente", empty: "Aguardando a primeira resposta do agente", noMatch: "Nenhuma mensagem encontrada.", restore: "O histórico desta conversa nativa está no terminal. Novas mensagens serão exibidas aqui.", storageError: "O armazenamento local está cheio. Exporte a conversa para preservar o histórico.", readOnly: "Planejamento · somente leitura", code: "Permissões do CLI", nativeHint: "Use o terminal para login, aprovações interativas e comandos / do CLI.", footer: "Enter envia · Shift+Enter quebra linha · Cole ou arraste imagens", runningSwitch: "Encerre o processo atual antes de trocar a interface", removeAttachment: "Remover anexo", minutes: "min", attachmentOnly: "Analise os arquivos anexados.", errorTitle: "Não foi possível concluir a resposta", saved: "Histórico salvo neste dispositivo", folder: "Referenciar pasta", openNative: "Abrir agente / entrar",
};
type Copy = typeof pt;
const en: Copy = {
  chat: "Chat", native: "Native terminal", ready: "Your next project starts here", intro: "Plan, build and review with your agents in one place.", latest: "Jump to latest", you: "You", attach: "Attach files or images", add: "Add context", files: "Files and images", goal: "Conversation goal", goalPlaceholder: "What outcome do you want to achieve?", goalHint: "Included in the next messages in this conversation.", sketch: "Sketch", sketchTitle: "Sketch for the agent", sketchAdd: "Attach sketch", clear: "Clear", cancel: "Cancel", remove: "Remove", drop: "Drop files to attach", upload: "Preparing attachments…", maxFiles: "Use up to 12 files, at most 20 MB each and 40 MB in total.", searching: "Search conversation", search: "Search", export: "Export conversation", copy: "Copy", copied: "Copied", retry: "Try again", starting: "Connecting to agent…", working: "Agent working…", stop: "Stop response", stopped: "Response interrupted", done: "Complete", tools: "Agent activity", empty: "Waiting for the agent's first response", noMatch: "No matching messages.", restore: "This native conversation's history is in the terminal. New messages will appear here.", storageError: "Local storage is full. Export the conversation to preserve its history.", readOnly: "Planning · read only", code: "CLI permissions", nativeHint: "Use the terminal for sign-in, interactive approvals and native / commands.", footer: "Enter to send · Shift+Enter for a new line · Paste or drop images", runningSwitch: "Stop the current process before switching interfaces", removeAttachment: "Remove attachment", minutes: "min", attachmentOnly: "Analyze the attached files.", errorTitle: "The response could not be completed", saved: "History saved on this device", folder: "Reference folder", openNative: "Open agent / sign in",
};
const es: Copy = {
  ...en, chat: "Conversación", native: "Terminal nativa", ready: "Tu próximo proyecto empieza aquí", intro: "Planifica, construye y revisa con tus agentes en un mismo lugar.", latest: "Ir al final", you: "Tú", attach: "Adjuntar archivos o imágenes", add: "Añadir contexto", files: "Archivos e imágenes", goal: "Objetivo de la conversación", goalPlaceholder: "¿Qué resultado quieres lograr?", goalHint: "Se incluye en los próximos mensajes de esta conversación.", sketch: "Dibujar", sketchTitle: "Boceto para el agente", sketchAdd: "Adjuntar boceto", clear: "Limpiar", cancel: "Cancelar", remove: "Eliminar", drop: "Suelta los archivos para adjuntarlos", upload: "Preparando adjuntos…", maxFiles: "Hasta 12 archivos, de 20 MB cada uno y 40 MB en total.", searching: "Buscar en la conversación", search: "Buscar", export: "Exportar conversación", copy: "Copiar", copied: "Copiado", retry: "Reintentar", starting: "Conectando con el agente…", working: "Agente trabajando…", stop: "Detener respuesta", stopped: "Respuesta interrumpida", done: "Completado", tools: "Actividad del agente", empty: "Esperando la primera respuesta del agente", noMatch: "No se encontraron mensajes.", restore: "El historial de esta conversación nativa está en la terminal. Los nuevos mensajes aparecerán aquí.", storageError: "El almacenamiento local está lleno. Exporta la conversación para conservarla.", readOnly: "Planificación · solo lectura", code: "Permisos del CLI", nativeHint: "Usa la terminal para iniciar sesión, aprobaciones interactivas y comandos / nativos.", footer: "Enter envía · Shift+Enter nueva línea · Pega o arrastra imágenes", runningSwitch: "Detén el proceso actual antes de cambiar de interfaz", removeAttachment: "Eliminar adjunto", attachmentOnly: "Analiza los archivos adjuntos.", errorTitle: "No se pudo completar la respuesta", saved: "Historial guardado en este dispositivo", folder: "Referenciar carpeta", openNative: "Abrir agente / iniciar sesión",
};
export function chatCopy(locale: string): Copy { return locale.startsWith("pt") ? pt : locale.startsWith("es") ? es : en; }
