const en = {
  context: "Conversation context", automatic: "Automatic compaction", prompts: "Prompt limit", tokens: "Context token limit", hint: "Compacts before the next request when either limit is reached. After compaction, waits for five new prompts before compacting again by token count. The provider may compact earlier. Your full chat history stays on this device.", compacting: "Compacting context…", estimated: "estimated tokens", measured: "context tokens", promptsSince: "prompts since compaction", compacted: "Compactions completed", older: "View earlier messages", latest: "Return to latest messages", page: "Showing up to 80 messages at a time. Search and export include saved history.", searchLimit: "Showing up to 80 matching messages.", historyError: "Could not read saved history. Please retry.", unsupported: "Automatic compaction is available in Claude Code and Codex chats.",
};
type Copy = typeof en;
const pt: Copy = {
  context: "Contexto da conversa", automatic: "Compactação automática", prompts: "Limite de prompts", tokens: "Limite de tokens de contexto", hint: "Compacta antes do próximo pedido ao atingir qualquer limite. Após compactar, aguarda cinco novos prompts para repetir pelo limite de tokens. O provedor pode compactar antes. O histórico completo permanece neste dispositivo.", compacting: "Compactando contexto…", estimated: "tokens estimados", measured: "tokens de contexto", promptsSince: "prompts desde a compactação", compacted: "Compactações concluídas", older: "Ver mensagens anteriores", latest: "Voltar às mensagens recentes", page: "Até 80 mensagens por vez. Busca e exportação incluem o histórico salvo.", searchLimit: "Exibindo até 80 mensagens encontradas.", historyError: "Não foi possível ler o histórico salvo. Tente novamente.", unsupported: "A compactação automática está disponível nas conversas com Claude Code e Codex.",
};
const es: Copy = {
  context: "Contexto de la conversación", automatic: "Compactación automática", prompts: "Límite de prompts", tokens: "Límite de tokens de contexto", hint: "Compacta antes de la siguiente solicitud al alcanzar cualquiera de los límites. Después, espera cinco prompts nuevos para repetir por tokens. El proveedor puede compactar antes. El historial completo permanece en este dispositivo.", compacting: "Compactando contexto…", estimated: "tokens estimados", measured: "tokens de contexto", promptsSince: "prompts desde la compactación", compacted: "Compactaciones completadas", older: "Ver mensajes anteriores", latest: "Volver a los mensajes recientes", page: "Hasta 80 mensajes a la vez. La búsqueda y la exportación incluyen el historial guardado.", searchLimit: "Mostrando hasta 80 mensajes encontrados.", historyError: "No se pudo leer el historial guardado. Reintenta.", unsupported: "La compactación automática está disponible en conversaciones con Claude Code y Codex.",
};
export function contextCopy(locale: string): Copy { return locale.startsWith("pt") ? pt : locale.startsWith("es") ? es : en; }
