const pt = { title: "Atualizações dos agentes", description: "Verificamos as versões ao abrir o app. Atualize o CLI para receber correções e consultar os modelos disponíveis para sua conta.", check: "Verificar atualizações", update: "Atualizar", checking: "Verificando…", updating: "Atualizando…", installed: "Instalada", latest: "Disponível", current: "Em dia", available: "Atualização disponível", missing: "Não detectada", updated: "CLI atualizado. Catálogo recarregado.", busy: "Encerre os agentes e terminais abertos no app para atualizar.", manual: "Instalação gerenciada externamente. Atualize pelo gerenciador usado na instalação.", unknown: "Falha ao verificar. Tente novamente.", network: "Não foi possível consultar o registro oficial. Verifique a conexão e tente novamente.", failed: "A atualização falhou. Confira permissões e outros processos usando o CLI e tente novamente.", unchanged: "A versão ativa ainda não é a disponível. Confira o caminho do CLI e o canal de atualização da instalação.", catalogue: "CLI atualizado, mas o catálogo não respondeu. Use Atualizar catálogo no seletor de modelo.", waiting: "Verificação pendente", source: "Canal latest · registro oficial npm", account: "Os modelos disponíveis também dependem da conta e da plataforma de cada provedor.", link: "Gerenciar atualizações dos CLIs", count: "atualizações dos CLIs", checked: "Última verificação" };
const en: typeof pt = { title: "Agent updates", description: "Versions are checked when the app opens. Update the CLI to receive fixes and query the models available to your account.", check: "Check for updates", update: "Update", checking: "Checking…", updating: "Updating…", installed: "Installed", latest: "Available", current: "Up to date", available: "Update available", missing: "Not detected", updated: "CLI updated. Model catalogue refreshed.", busy: "Stop agents and terminals running in the app before updating.", manual: "Externally managed installation. Update with its original package manager.", unknown: "Check failed. Try again.", network: "Could not reach the official registry. Check your connection and retry.", failed: "Update failed. Check permissions and other processes using the CLI, then retry.", unchanged: "The active version is still behind. Check the CLI path and the installation's release channel.", catalogue: "CLI updated, but the catalogue did not respond. Use Refresh catalogue in the model picker.", waiting: "Check pending", source: "Latest channel · official npm registry", account: "Available models also depend on each provider's account and platform.", link: "Manage CLI updates", count: "CLI updates", checked: "Last checked" };
const es: typeof pt = { title: "Actualizaciones de agentes", description: "Comprobamos las versiones al abrir la app. Actualiza el CLI para recibir correcciones y consultar los modelos de tu cuenta.", check: "Buscar actualizaciones", update: "Actualizar", checking: "Comprobando…", updating: "Actualizando…", installed: "Instalada", latest: "Disponible", current: "Al día", available: "Actualización disponible", missing: "No detectada", updated: "CLI actualizado. Catálogo recargado.", busy: "Detén los agentes y terminales de la app antes de actualizar.", manual: "Instalación externa. Actualiza con el gestor original.", unknown: "No se pudo comprobar. Reintenta.", network: "No se pudo consultar el registro oficial. Comprueba la conexión.", failed: "Falló la actualización. Comprueba los permisos y otros procesos que usan el CLI.", unchanged: "La versión activa sigue siendo anterior. Revisa la ruta y el canal de actualización.", catalogue: "CLI actualizado; el catálogo no respondió. Actualízalo desde el selector de modelo.", waiting: "Comprobación pendiente", source: "Canal latest · registro oficial npm", account: "Los modelos dependen también de la cuenta y plataforma del proveedor.", link: "Gestionar actualizaciones de CLI", count: "actualizaciones de CLI", checked: "Última comprobación" };
export const cliUpdateCopy = (locale: string) => locale.startsWith("pt") ? pt : locale.startsWith("es") ? es : en;
const installerErrors = {
  pt: { cli_path_error: "O npm não conseguiu interpretar o caminho da instalação. Instale a versão mais recente do Agentdeck e tente novamente.", cli_disk_full: "Não há espaço suficiente no disco para instalar a atualização.", cli_permission_denied: "O npm não tem permissão de escrita na pasta do CLI. Confira as permissões dessa instalação.", cli_files_in_use: "O sistema bloqueou um arquivo do CLI (EPERM/EBUSY). Feche processos externos que usem esse CLI, confira as permissões da pasta e tente novamente.", cli_certificate_error: "A conexão com o registro npm falhou na verificação do certificado. Confira o certificado da rede ou do proxy.", cli_registry_access: "O registro npm recusou o acesso. Confira a autenticação do npm e as regras de rede.", cli_timeout: "A atualização excedeu o tempo limite. Verifique a conexão e tente novamente.", exit: "Código de saída" },
  en: { cli_path_error: "npm could not interpret the installation path. Install the latest Agentdeck version and retry.", cli_disk_full: "There is not enough disk space to install the update.", cli_permission_denied: "npm cannot write to the CLI folder. Check this installation's permissions.", cli_files_in_use: "The system blocked a CLI file (EPERM/EBUSY). Close external processes using this CLI, check folder permissions and retry.", cli_certificate_error: "Certificate verification failed when connecting to npm. Check the network or proxy certificate.", cli_registry_access: "The npm registry denied access. Check npm authentication and network rules.", cli_timeout: "The update timed out. Check your connection and retry.", exit: "Exit code" },
  es: { cli_path_error: "npm no pudo interpretar la ruta. Instala la última versión de Agentdeck y reintenta.", cli_disk_full: "No hay espacio suficiente en el disco para instalar la actualización.", cli_permission_denied: "npm no puede escribir en la carpeta del CLI. Revisa los permisos de la instalación.", cli_files_in_use: "El sistema bloqueó un archivo del CLI (EPERM/EBUSY). Cierra los procesos externos que lo usan, revisa los permisos y reintenta.", cli_certificate_error: "Falló la verificación del certificado al conectar con npm. Revisa el certificado de la red o del proxy.", cli_registry_access: "El registro npm denegó el acceso. Revisa la autenticación de npm y las reglas de red.", cli_timeout: "La actualización superó el tiempo límite. Revisa la conexión y reintenta.", exit: "Código de salida" },
};
export function cliUpdateError(error: string, c: typeof pt) {
  const extra = c === pt ? installerErrors.pt : c === es ? installerErrors.es : installerErrors.en;
  const code = error.replace(/^Error:\s*/, "").split(":")[0];
  const detail = Object.prototype.hasOwnProperty.call(extra, code) && code !== "exit" ? extra[code as keyof typeof extra] : undefined;
  const message = detail || (error.includes("network_unavailable") ? c.network : /cli_busy|cli_updating/.test(error) ? c.busy : error.includes("unsupported_installation") ? c.manual : error.includes("cli_version_unchanged") ? c.unchanged : error.includes("catalogue_unavailable") ? c.catalogue : error.includes("cli_unavailable") ? c.missing : c.failed);
  const exit = /:exit=(-?\d+)\b/.exec(error)?.[1];
  return exit ? `${message} ${extra.exit}: ${exit}.` : message;
}
