const pt = {
  retry: "Tentar novamente", noMatches: "Nenhuma nota encontrada para esta busca.",
  sourceHint: "Escolha uma pasta para habilitar a busca.", choosing: "Escolhendo pasta…",
  clearing: "Removendo fonte…", results: "Resultados", preview: "Trecho da nota",
  updated: "Fonte atualizada.", removed: "Fonte removida. Os arquivos foram preservados.",
  scope: "Escopo dos documentos", global: "Global", project: "Projeto", projectLabel: "Projeto dos documentos",
  globalHint: "Pasta Markdown ou vault com conhecimentos gerais para todos os projetos.",
  projectHint: "Markdown ou vault deste projeto. As tarefas usam trechos relevantes desta fonte e da global, dentro do limite de contexto.",
  noProject: "Selecione um projeto para configurar seus documentos.", storage: "Configuração salva em", original: "As notas permanecem na pasta original; o índice é local e fica em memória.",
  graph: "Grafo de notas", refresh: "Atualizar índice", notes: "notas", links: "ligações", graphHint: "Conexões de [[wikilinks]] e links Markdown. Selecione uma nota para ver seu trecho e suas conexões.",
  noNotes: "Nenhum arquivo .md ou .markdown nesta pasta.", noLinks: "Adicione [[Nome da nota]] ou [nome](nota.md) para conectar suas notas.",
  graphLimit: "A fonte excede o limite do índice. Escolha uma pasta mais específica.",
  indexLimit: "Índice limitado a 3.000 notas, 16 MB de texto e 256 KB por arquivo. Prefira uma pasta mais específica para incluir os documentos desejados.",
  chooseNote: "Selecionar nota", connections: "Notas conectadas", noConnections: "Esta nota ainda não possui conexões.",
  cacheHint: "O índice reaproveita arquivos sem alterações. Atualizar verifica mudanças feitas na pasta.",
};
const en: typeof pt = {
  retry: "Try again", noMatches: "No notes match this search.",
  sourceHint: "Choose a folder to enable search.", choosing: "Choosing a folder…",
  clearing: "Removing source…", results: "Results", preview: "Note excerpt",
  updated: "Source updated.", removed: "Source removed. Your files were kept.",
  scope: "Document scope", global: "Global", project: "Project", projectLabel: "Document project",
  globalHint: "A Markdown folder or vault with general knowledge for all projects.",
  projectHint: "This project's Markdown folder or vault. Tasks use relevant excerpts from this source and the global source within the context limit.",
  noProject: "Select a project to configure its documents.", storage: "Configuration saved in", original: "Notes stay in the original folder; the local index is kept in memory.",
  graph: "Note graph", refresh: "Refresh index", notes: "notes", links: "links", graphHint: "Connections from [[wikilinks]] and Markdown links. Select a note to see its excerpt and connections.",
  noNotes: "No .md or .markdown files in this folder.", noLinks: "Add [[Note name]] or [name](note.md) to connect your notes.",
  graphLimit: "The source exceeds the index limit. Narrow the source folder.",
  indexLimit: "Index limited to 3,000 notes, 16 MB of text and 256 KB per file. Choose a more specific folder to include the documents you need.",
  chooseNote: "Select a note", connections: "Connected notes", noConnections: "This note has no connections yet.",
  cacheHint: "The index reuses unchanged files. Refresh checks for changes in the folder.",
};
const es: typeof pt = {
  retry: "Reintentar", noMatches: "No se encontraron notas para esta búsqueda.",
  sourceHint: "Elige una carpeta para habilitar la búsqueda.", choosing: "Eligiendo carpeta…",
  clearing: "Quitando fuente…", results: "Resultados", preview: "Fragmento de la nota",
  updated: "Fuente actualizada.", removed: "Fuente eliminada. Los archivos se conservaron.",
  scope: "Ámbito de documentos", global: "Global", project: "Proyecto", projectLabel: "Proyecto de documentos",
  globalHint: "Carpeta Markdown o vault con conocimientos generales para todos los proyectos.",
  projectHint: "Markdown o vault de este proyecto. Las tareas usan fragmentos relevantes de esta fuente y la global dentro del límite de contexto.",
  noProject: "Selecciona un proyecto para configurar sus documentos.", storage: "Configuración guardada en", original: "Las notas permanecen en la carpeta original; el índice local se mantiene en memoria.",
  graph: "Grafo de notas", refresh: "Actualizar índice", notes: "notas", links: "enlaces", graphHint: "Conexiones de [[wikilinks]] y enlaces Markdown. Selecciona una nota para ver su fragmento y conexiones.",
  noNotes: "No hay archivos .md o .markdown en esta carpeta.", noLinks: "Añade [[Nombre de nota]] o [nombre](nota.md) para conectar tus notas.",
  graphLimit: "La fuente supera el límite del índice. Elige una carpeta más específica.",
  indexLimit: "Índice limitado a 3.000 notas, 16 MB de texto y 256 KB por archivo. Elige una carpeta más específica para incluir los documentos necesarios.",
  chooseNote: "Seleccionar nota", connections: "Notas conectadas", noConnections: "Esta nota aún no tiene conexiones.",
  cacheHint: "El índice reutiliza archivos sin cambios. Actualizar comprueba los cambios en la carpeta.",
};
export const knowledgeCopy = (locale: string) => locale === "pt-BR" ? pt : locale === "es-ES" ? es : en;
